# Generated by Django 5.0.7 on 2024-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/avatar-default-icon.png', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
