# Generated by Django 5.0.7 on 2024-07-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alumni_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/avatar-default-icon.png', null=True, upload_to='avatars/'),
        ),
    ]
