# Generated by Django 5.0.7 on 2024-07-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_alumni_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
