# Generated by Django 5.0.7 on 2024-07-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alumni_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='date_created',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=15)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Complete', 'Complete')], max_length=15)),
                ('file', models.FileField(upload_to='diploma-tor/')),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.alumni')),
            ],
        ),
    ]
