# Generated by Django 5.0.7 on 2024-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_alumni_date_created_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='diploma-tor/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Complete', 'Complete')], max_length=25),
        ),
    ]
