# Generated by Django 5.0.7 on 2024-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_request_file_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='file_type',
            field=models.CharField(max_length=25),
        ),
    ]
