# Generated by Django 5.0.7 on 2024-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
