# Generated by Django 5.0.7 on 2024-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
