# Generated by Django 5.0.7 on 2024-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_job_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
