# Generated by Django 5.0.7 on 2024-07-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_request_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
